[package]
name = "hbr"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
webpage = "1.4.0"

[profile.dev]
opt-level = 0

[profile.release]
lto = true
opt-level = 3
